### nginxでphpをブラウザ上に表記するのに必要なコンテナ一式。
version: '3'
services:
  app:
    image: laradock/php-fpm:2.2-7.2
    volumes:
      - ./:/var/phpapp/

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/phpapp/

  ### host:127.0.0.1 user:root
  mysql:
    image: mysql:5.7
    ports:
      - 33306:3306
    volumes:
      - ./testdata/:/data
    environment:
        MYSQL_DATABASE: app
        MYSQL_ROOT_PASSWORD: root
